### PR TITLE
Goods

### PR DESCRIPTION
**Pull request by arun-muralidharan**
#74 #75 #76 #77

Implemented goods.

Known bugs/discrepancies:

- There is a visual glitch in the unit selection button; the button disappears when the goods name field is out of focus. I'm not sure why this is happening and it was taking too much time to debug. It does not hinder functionality; so, I'll fix this later.
- In unit selection screen, the UI for dropdown selection is not exactly as it is in the design; again, I was facing a few bugs with the custom dropdown widget. So, for now I have implemented it using the basic dropdown widget and it is functional. I'll fix the custom dropdown later.

### CODE REVIEW

**Comment by Vedsaga** [comment]
Anna, could I merged this?

**Review by Vedsaga — APPROVED** [review]

**Comment by arun-muralidharan** [comment]
> Anna, could I merged this? 

Sure! It should work. Let me know if there are any issues after you test it. :+1:

**Comment by Vedsaga** [comment]
> > Anna, could I merged this?
> 
> Sure! It should work. Let me know if there are any issues after you test it.

Okay Anna sure 👍

**Comment by Vedsaga** [comment]
Anna, just edit Goods was not working... Rest everything was working...

**Comment by Vedsaga** [comment]
Anna, in the  view_goods Api `Location_ID` is replaced with `Location_name` and it's deployed.
.  So, it's not working on app for time being...

**Pull request merged**
