### PR TITLE
API Changes & Verification Redirection

### PR DESCRIPTION
**Pull request by arun-muralidharan**
#3 #9

- Request and response models changed to reflect the recent API changes.
- Email verification page now pings the server every 5 seconds to see if the user is verified, and redirects to success page automatically.
	- The ping happens only if the app is active; it is suspended if the app is in the background or inactive (screen goes off). This will ensure the app does not keep pinging the server perpetually.
- Verification does not work with regenerated OTP ; this is likely to be fixed when it is fixed in the backend.

### CODE REVIEW

**Review by imssurya — APPROVED** [review]

**Comment by Vedsaga** [comment]
> * Verification does not work with regenerated OTP ; this is likely to be fixed when it is fixed in the backend.*

Is this the case for worker or owner or both?

**Comment by arun-muralidharan** [comment]
> Is this the case for worker or owner or both?

I just tested for owner, and it works for owner. So, only worker.

**Comment by arun-muralidharan** [comment]
Tested on worker, and that works too. I'm guessing it is fixed.

**Comment by Vedsaga** [comment]
I guess, it's not fixed because I requested for OTP and I didn't filled the OTP and still I received the mail saying your account is created, neither I clicked on link nor I filled the OTP and also, in Flutter app when I click on Resend OTP it's letting me send the OTP request however, it should not supposed to stuck at OTP screen once user mail verify. In current case as account is getting verified automatically without clicking on **link** or **filling OTP** so, that's why in the app I have to close the app and try logging again.

Screenshot_20210729_172610
Screenshot_20210729_172616

**Pull request merged**
